site_name: Atheios docs
site_description: Documentation for the Atheios project
theme: readthedocs
nav:
    - 'index.md'
    - 'introduction.md'
    - 'start.md'
    - 'api.md'
    - 'api/garp.md'
    - 'api/portal.md'
    - 'api/api.md'
    - 'gamedev_modules.md'
    - 'resources.md'
    - 'gath.md'
